import turtle

turtle.shape("turtle")
turtle.penup()
turtle.setx(-300)
turtle.pendown()
# p
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(180)

turtle.penup()
turtle.forward(100)
turtle.pendown()
# y
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(180)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)

turtle.penup()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.pendown()
# t
turtle.forward(100)
turtle.right(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)

turtle.penup()
turtle.forward(50)
turtle.pendown()

turtle.left(90)
turtle.forward(100)
turtle.left(180)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)

turtle.penup()
turtle.left(90)
turtle.forward(50)
turtle.pendown()

# o
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)

turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.pendown()
# n
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)

turtle.exitonclick()
